function log(...objects) { console.log(`Jolt: ${objects.join(" ")}`) }
log("Jolt loaded!")

// embed ui into editor
function jEmbedEditorUI()
{
    let topRightMenu = document.querySelector(".right-top-menu")
    if (topRightMenu)
    {
        log("In editor - appending UI")

        let transferElement = document.createElement("div")
        transferElement.style.display = "none"
        transferElement.id = "jTransferElement"
        document.body.appendChild(transferElement)


        let a = document.createElement("a")
        a.classList.add("button", "hover-zoom105", "brad5", "jolt-insert-js")

        a.innerText = "Insert javascript (Jolt)"

        let textarea = document.createElement("textarea")

        textarea.style.resize = "none"
        textarea.style.width = "240px"
        textarea.style.display = "block" // put on next line, easier than creating a <br/>

        textarea.addEventListener("keyup", event => {
            // some jquery library prevents spaces from being
            // typed in textareas and inputs
            // this just overrides it and fixes it
            if (event.code == "Space")
                insertAtCursor(textarea, " ")
        })
        textarea.addEventListener("keyup", event => event.stopImmediatePropagation()) // prevent keybinds happening
        
        a.appendChild(textarea)

        let button = document.createElement("button")
        button.innerText = "Inject"

        button.addEventListener("click", event => {
            event.stopPropagation()
            log("Clicked insert javascript btn")

            jInsertCustomJavascript(textarea.value)
        })

        // workaround for not being able to see window.level from chrome extension
        // add window.level data to DOM on button press
        button.setAttribute("onclick", "document.querySelector('#jTransferElement').innerHTML = JSON.stringify(window.level)")

        a.appendChild(button)

        topRightMenu.appendChild(a)
    }
}

// tests if the ui is gone and if so add it to the dom again
function jPollJoltEditorUI()
{
    let joltEditorJSButton = document.querySelector(".jolt-insert-js")
    if (!joltEditorJSButton)
        jEmbedEditorUI()
}

// called when you press the "inject javascript" button
function jInsertCustomJavascript(js)
{
    let i = setInterval(() => {
        // poll if window.level is in DOM
        if (document.querySelector("#jTransferElement").innerHTML != "")
        {
            // ready to go
            clearInterval(i)

            let guid = window.location.pathname.replace("/", "") // dont convert to number - precision is lost

            log("Injecting javascript\nguid=" + guid + "\njs=" + js)

            let level = JSON.parse(document.querySelector("#jTransferElement").innerHTML)

            level.jolt = {
                "metadata": "jolt-0.1|dev=true",
                "script": js.replaceAll("\"", "\\\"")
            }

            // generated by "copy as fetch" from chrome devtools
            fetch(`https://www.supersparkmaker.com/levels/save/${guid}/`, {
                "headers": {
                    "accept": "*/*",
                    "accept-language": "en-GB,en-US;q=0.9,en;q=0.8,ja;q=0.7,sq;q=0.6,fr;q=0.5",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "sec-ch-ua": "\"Chromium\";v=\"118\", \"Google Chrome\";v=\"118\", \"Not=A?Brand\";v=\"99\"",
                    "sec-ch-ua-mobile": "?0",
                    "sec-ch-ua-platform": "\"Windows\"",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-origin",
                    "x-requested-with": "XMLHttpRequest"
                },
                "referrer": "https://www.supersparkmaker.com/1697150485280988308",
                "referrerPolicy": "strict-origin-when-cross-origin",
                "body": `save=false&data=${JSON.stringify(level)}`,
                "method": "POST",
                "mode": "cors",
                "credentials": "include"
            })
        }
    }, 5) // shouldnt take too long
}

function jMain()
{
    setInterval(jPollJoltEditorUI, 500)
    
    jPollJoltEditorUI()

    // test if level has scripts
    if (window.location.pathname != "/create")
    {
        let levelAsString = document.querySelector(".gameWrap").querySelector("script").innerHTML
        levelAsString = levelAsString
        // remove extra stuff:
        .replace(`var powerUp = '';
		window.level = false; window.level = JSON.parse('`, "")
        .replace(`');window.uploaded = false;`, "")

        let level = JSON.parse(levelAsString)

        if (level.jolt)
        {
            // yes has scripts!
            // prompt user if they want to enable them (also need button for onclick event) edit: me from the future: I could use an image with an onerror to run code without user interaction, might have to implement that
            let promptElement = document.createElement("div")
            promptElement.style.top = "5px"
            promptElement.style.left = "5px"
            promptElement.style.position = "fixed"
            promptElement.style.width = "40vw"
            promptElement.style.height = "10vh"
            promptElement.style.display = "inline-flex"
            promptElement.style.zIndex = "6969" // hehe
            promptElement.style.fontFamily = "var(--font-family) !important"
            promptElement.style.transition = "2s ease top"
            
            promptElement.id = "jPromptElement"

            promptElement.classList.add("button", "brad5")

            promptElement.innerText = "This level contains custom javascript, would you like to enable it?"

            let button = document.createElement("div")
            button.style.display = "inline-block"
            button.style.cursor = "pointer"

            button.classList.add("button", "hover-zoom105", "brad5")
            button.innerText = "Yes"
            button.setAttribute("onclick", "eval(window.level.jolt.script);document.querySelector(\"#jPromptElement\").style.top = \"-100%\"")

            promptElement.appendChild(button)
            
            document.body.appendChild(promptElement)
        }
    }
}

jMain()

